sudo: required

services:
  - docker

language: bash

notifications:
  email:
    recipients:
      - travis@23-5.eu
    on_success: always
    on_failure: always

script:
  - cp -r python   docker/robot
  - cp -r protobuf docker/robot
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset 
  - docker build -t ansi/antikeimenarobot:latest docker/robot/
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push ansi/antikeimenarobot:latest
